### PR TITLE
fix(onerc): use relative paths

### LINKED ISSUE #1383: `yarn neo-one init` paths should be relative
### Description

`yarn neo-one init` generates absolute paths

### Steps to Reproduce

1. `npx create-react-app token --typescript`
2. add neo-one deps
3. `yarn neo-one init`

**Expected behavior:** relative paths are added to the configuration for contracts/generated

**Actual behavior:** absolute paths are used

**Reproduces how often:** 100%

### Versions

v1.1.2

### Additional Information

Nada

### PR DESCRIPTION
**Pull request by davemneo**
fix #1383

### Requirements

Use relative paths in the `.onerc`

### Description of the Change

utilize `path.relative()`,
explicitly `spread` the part of the config that's used: `codegen` after scrubbing `paths`
### Test Plan

    yarn neo-one init
    // review .onerc

### Applicable Issues
#1383

### CODE REVIEW

File: packages/neo-one-server-plugin-project/src/initCommand.ts [hunk 1]
```diff
@@ -34,8 +34,16 @@ export const initCommand = ({ cli }: InteractiveCLIArgs) =>
   cli.vorpal.command('init', 'Initialize neo-one in the current directory.').action(async () => {
     const cwd = process.cwd();
     const projectConfig = await loadProjectConfig(cwd);
-    const tsconfigPath = path.resolve(projectConfig.paths.contracts, 'tsconfig.json');
+    const relativeConfig = {
```
Comment (dicarlo2) [inline packages/neo-one-server-plugin-project/src/initCommand.ts]: let's just spread the remaining properties so that we don't forget to update this if we add more to the `ProjectConfig` later:

```
const relativeConfig = {
  ...projectConfig,
  paths: {
    ...projectConfig.paths,
    contracts: path.relative(process.cwd(), projectConfig.paths.contracts),
    generated: path.relative(process.cwd(), projectConfig.paths.generated),    
  },
};
```

Comment (davemneo) [reply packages/neo-one-server-plugin-project/src/initCommand.ts]: When I did the spread, I had my order backwards, Thnx.
